// In-memory data store with realistic initial data matching provided UI specs

export const memoryStore = {
  users: [
    {
      id: 'usr_admin',
      name: 'Senior Atelier Admin',
      email: 'admin@threadandstyle.com',
      phone: '+1 (555) 019-2834',
      passwordHash: '$2a$10$wT.N3hY/HqYgD0S8xR/dI.BwT3lR9H7MvYw6eJ6H/gIeY5x8M7g5K', // password123
      role: 'admin',
      membership: 'Atelier Master',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-TsLpnT60pzCT1dQxlTs22TStCCZywZFw15xJXw96JRCiNLMgun25yAn1dH5IHj3w3fZV9u_ZheV2MJ5p1MDxANCXUNT2eN9e79SlPozxuKp91VKnT24Om63tKkUHKJErUKjvpZCVfuXHZ0a5M67B9AoHQytiB68TCIfAEUw6krAhCQzz1OrhfcCT3ETQt50lzQ1lubeYLJTgckbsXgxKaaPJv_KYHRdW5QBp-nQa2nDU1reo81c',
      measurements: { chest: '40.5"', waist: '34.0"', shoulder: '18.5"', sleeveLength: '25.0"' },
      createdAt: new Date().toISOString(),
    },
    {
      id: 'usr_alexander',
      name: 'Alexander Wright',
      email: 'alexander@example.com',
      phone: '+1 (555) 019-2834',
      passwordHash: '$2a$10$wT.N3hY/HqYgD0S8xR/dI.BwT3lR9H7MvYw6eJ6H/gIeY5x8M7g5K', // password123
      role: 'customer',
      membership: 'Premium Member',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-TsLpnT60pzCT1dQxlTs22TStCCZywZFw15xJXw96JRCiNLMgun25yAn1dH5IHj3w3fZV9u_ZheV2MJ5p1MDxANCXUNT2eN9e79SlPozxuKp91VKnT24Om63tKkUHKJErUKjvpZCVfuXHZ0a5M67B9AoHQytiB68TCIfAEUw6krAhCQzz1OrhfcCT3ETQt50lzQ1lubeYLJTgckbsXgxKaaPJv_KYHRdW5QBp-nQa2nDU1reo81c',
      measurements: { chest: '40.5"', waist: '34.0"', shoulder: '18.5"', sleeveLength: '25.0"' },
      createdAt: new Date().toISOString(),
    },
  ],

  services: [
    {
      id: 'srv_1',
      name: 'Bespoke Suit & Blazer Tailoring',
      category: 'Bespoke',
      gender: 'Men',
      description: 'From initial pattern drafting to final pressing, a truly unique garment constructed entirely for your physique.',
      price: '$1,200 - $3,500',
      active: true,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPo95bZLCT8FfKIJSlDptBzD7Cw0zt-y5gj9G0p7qxClsbXE12se5f6BF-z5RsWPcZ547xaZVY7Cuz9B_GenP--H1wzvr_ghnY5IFwPdIt-jI0nCfe1n9bI1MlsCfHXLkq4Ak4rfcN1cwAds-MFjH3x2yszB2Vr_1ONaeb1Q8JNFQMKrGHWufkC4Bp2ycucw5O9SeWO6MIXBfyUqfezIPIWIwatG5fdmleIh5YtLOljd5xXdC5z_4',
    },
    {
      id: 'srv_2',
      name: 'Luxury Alterations & Reshaping',
      category: 'Alterations',
      gender: 'Unisex',
      description: 'Precision tailoring to adjust shoulder width, hemline, sleeve tapering, and waist contouring on luxury garments.',
      price: '$80 - $450',
      active: true,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAjq_7_sxFZoHVMLvL6PAUy2uSK3RbggjB33-loaqUasITC1RRzxr2qoSYMRm6zgTdCm3xrL3II_rRDAv3IB_byWSxNM5Oghavf_wUG2PTyX0rwqZm6hyQnQ5imjnvkmM8ZWvj35n6CzUeNSYm4EOVp7leG9PDCoq9tTfbq9ibJnf0LcrJcAqWiBnZQkKqcTDz70guJTP3LGFg9Vi0-AxgNs6fNqB8Jik1rhRIc_s3DLJKx-90lN8w',
    },
    {
      id: 'srv_3',
      name: 'Bespoke Bridal & Evening Gowns',
      category: 'Bridal',
      gender: 'Women',
      description: 'Hand-stitched bespoke bridal couture featuring delicate lace, beadwork, and custom silk corsetry.',
      price: '$1,800 - $5,000',
      active: true,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA39UQCw73UVOrQVQW0pLXY5MIN6nqJvW0gc8MUTdhZzNHuoQEyLQPM2832Qrg0z-OnhjeImAJg4tLZnqyKwWTPc9m_4kk9j165KXJf-81axo3s7tkmkH9y_ycECRsLRW_IJDO9WcZ2LNPs8DpTSa945f01RrDIkrEqMwz6gu-xVyOqj94CjOvdld1bLxP-97CRVoo-SJGa-wLH-M-yC0ZQiOq2hw7fFuOQS_aq2FueUJdz5VFaQH0',
    },
    {
      id: 'srv_4',
      name: 'Doorstep Fitting & Personal Styling',
      category: 'Doorstep',
      gender: 'Unisex',
      description: 'Our master tailor travels directly to your home or office with fabric swatches, sample coats, and tape measure.',
      price: '$250 Service Fee',
      active: true,
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXmlnlCQSTOQorBEvIzbl0ZM_ypc3uF7rkU9mplr3QFKveRLD54TBl84kTaT0SzcVAqSpJKv9NYDgmoBXHW_2RfC294tNk6CUJR9NkHO-xIejpDOVh98-w4p4OnjU8hsqIZzWRVJfy2phWeDKOug9XU4gVPUY2KeLzhPDptRCdjf94h7VZ1qiCjnEIz_p-v9GDr1j1-rV2QOpuM5FEVDqSpIFGwNOQ3h8hQ_LNQF3jVnRBNwrFUKo',
    },
  ],

  consultations: [
    {
      id: 'c_101',
      customerId: 'usr_alexander',
      customerName: 'Alexander Wright',
      email: 'alexander@example.com',
      phone: '+1 (555) 019-2834',
      service: 'Initial Fitting - Bespoke Suit',
      date: '2026-10-24',
      time: '14:00 - 15:30',
      location: 'London Flagship Atelier',
      requirements: 'Initial consultation for 3-piece Navy Flannel Suit.',
      status: 'Confirmed',
      referenceId: 'TS-2026-000124',
      createdAt: '2026-10-01T10:00:00Z',
    },
    {
      id: 'c_102',
      customerId: 'usr_alexander',
      customerName: 'Alexander Wright',
      email: 'alexander@example.com',
      phone: '+1 (555) 019-2834',
      service: 'Final Collection - Flannel Suit',
      date: '2026-11-05',
      time: '10:00 - 11:00',
      location: 'London Flagship Atelier',
      requirements: 'Final fitting and garment pickup.',
      status: 'Pending',
      referenceId: 'TS-2026-000188',
      createdAt: '2026-10-05T14:30:00Z',
    },
  ],

  tailoringRequests: [
    {
      id: 'tr_201',
      referenceId: 'REQ-2026-8812',
      customerId: 'usr_alexander',
      customerName: 'Alexander Wright',
      email: 'alexander@example.com',
      phone: '+1 (555) 019-2834',
      category: 'Bespoke',
      gender: 'Men',
      garmentType: 'Navy Flannel 3-Piece Suit',
      requirements: 'Textured weave Italian wool, horn buttons, peak lapels.',
      measurements: { chest: '40.5"', waist: '34.0"', shoulder: '18.5"', sleeveLength: '25.0"' },
      referenceImages: [
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCAVgt2nNxfJdHqZInVW8rSj7YNDPVE5HzioHIblQNq2rS1vhEcnEE8EIrYQQLupn5kgB95GMNNsxQVqs-Ijrh2L5Apm3UFQmJ3J5irwvMPPVcbeGuRgsh5ifs9TPdzqxcrBSzHlMTElQR7_CMvRKoJ7kU13NkScfJvp-IrB6HZKVb74R__90pai_4peuZpZbdK9D96dbHEGkTtXAd8d3e6ccebuxoPoHAfQERm3TyL_QzGo274NNQ',
      ],
      status: 'In Progress',
      assignedTailor: 'Master Tailor Giovanni',
      quotation: '$2,850.00',
      expectedCompletionDate: '2026-11-05',
      notes: [
        { text: 'Fabric swatches approved by customer.', author: 'S. Taylor', createdAt: new Date().toISOString() }
      ],
      createdAt: '2026-09-12T09:00:00Z',
    },
  ],

  leads: [
    {
      id: 'ld_1284',
      leadId: '1284',
      customerId: 'usr_sterling',
      name: 'Alexander Sterling',
      phone: '+1 (555) 019-2834',
      email: 'a.sterling@email.com',
      service: 'Bespoke Suit (3-Piece)',
      requirements: 'Looking for a custom navy wool suit for an upcoming winter wedding. Interested in exploring fabric options from Italian mills, specifically textured weaves. Would like to schedule an initial fitting next week if possible.',
      source: 'Instagram Campaign',
      status: 'Quote Sent',
      assignedTo: 'S. Taylor',
      followUpDate: '2026-10-30',
      inspirationPhotos: [
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCAVgt2nNxfJdHqZInVW8rSj7YNDPVE5HzioHIblQNq2rS1vhEcnEE8EIrYQQLupn5kgB95GMNNsxQVqs-Ijrh2L5Apm3UFQmJ3J5irwvMPPVcbeGuRgsh5ifs9TPdzqxcrBSzHlMTElQR7_CMvRKoJ7kU13NkScfJvp-IrB6HZKVb74R__90pai_4peuZpZbdK9D96dbHEGkTtXAd8d3e6ccebuxoPoHAfQERm3TyL_QzGo274NNQ',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuAygpPL7V9NEcnssLApgW5xzDm6HDdQltaD26SVEautn6VTNuon7FvkFkaDU9R9hcUv5Wv6EHu33NbMdXBCyIz0mU7gQgSrnOQqzGVYne3VYBmHVaU1x7CqoUR40JFjR3JL5-82DUiULNfcb8QLe51g7l0nJ-nhZwRkBGKOQDKQwpblyA3sZLKdylY0PNi5TWE9yluzj_aPNKnan4V4hhijTX1BT5aIUpxxO3dcEXkqgK3TzX1SXiM',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuD0gEgASp8VD3KClbV0Y9ghm-DMAhyICdxYerMujfCyhdqx5DgBc8bsqk_Cyp1MB7XRcLD8kxoRj_eak62Iex4ujaFBvCdodJdElwQ8tPNEhZlobn81JiPiRmxVVDXlvsi9G50FROPuFwMmbdvOFjvMVhqGM_vVyWaftk_4fHXlsAmX5oeggHawTx9OimUzjvKWeCM0q-cfI6XFW6Q212RrhN9UXKtkiDsnV-H_WEtoXny6TSECWF0',
      ],
      notes: [
        {
          text: 'Sent initial quote document via email. Included swatch samples for navy herringbone.',
          author: 'S. Taylor',
          createdAt: new Date('2026-10-25T09:15:00').toISOString(),
        },
      ],
      createdAt: '2026-10-24T11:20:00Z',
    },
    {
      id: 'ld_092',
      leadId: '092',
      customerId: '',
      name: 'Eleanor Vance',
      phone: '+1 (555) 482-9901',
      email: 'e.vance@couture.org',
      service: 'Bespoke Suit',
      requirements: 'Tweed double-breasted suit tailored for autumn gallery opening.',
      source: 'Referral',
      status: 'New',
      assignedTo: 'Unassigned',
      followUpDate: '',
      inspirationPhotos: [],
      notes: [],
      createdAt: '2026-10-26T14:10:00Z',
    },
    {
      id: 'ld_091',
      leadId: '091',
      customerId: '',
      name: 'Arthur Pendelton',
      phone: '+1 (555) 302-8812',
      email: 'arthur.p@heritage.co.uk',
      service: 'Alterations',
      requirements: 'Restoring vintage Savile Row tuxedo coat lapel and waistline.',
      source: 'Direct Website',
      status: 'Contacted',
      assignedTo: 'Master Tailor Giovanni',
      followUpDate: '2026-10-29',
      inspirationPhotos: [],
      notes: [{ text: 'Customer requested doorstep consultation.', author: 'Admin', createdAt: new Date().toISOString() }],
      createdAt: '2026-10-24T08:45:00Z',
    },
    {
      id: 'ld_090',
      leadId: '090',
      customerId: '',
      name: 'Clara Hughes',
      phone: '+1 (555) 918-3341',
      email: 'clara.h@design.com',
      service: 'Bridal Styling',
      requirements: 'Silk crepe gown alteration and custom veil creation.',
      source: 'Instagram',
      status: 'In Progress',
      assignedTo: 'Elena S.',
      followUpDate: '2026-11-02',
      inspirationPhotos: [],
      notes: [],
      createdAt: '2026-10-22T16:30:00Z',
    },
    {
      id: 'ld_089',
      leadId: '089',
      customerId: '',
      name: 'Marcus Thorne',
      phone: '+1 (555) 701-4492',
      email: 'm.thorne@luxury.net',
      service: 'Wardrobe Consultation',
      requirements: 'Complete winter wardrobe bespoke tailoring package.',
      source: 'VIP Member',
      status: 'Contacted',
      assignedTo: 'S. Taylor',
      followUpDate: '2026-10-28',
      inspirationPhotos: [],
      notes: [],
      createdAt: '2026-10-20T10:00:00Z',
    },
  ],
};
