/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
        "inverse-primary": "#c8c6c5",
        "secondary": "#5e5f5d",
        "on-secondary": "#ffffff",
        "secondary-container": "#e0e0dd",
        "on-secondary-container": "#626361",
        "secondary-fixed": "#e3e2e0",
        "secondary-fixed-dim": "#c7c6c4",
        "on-secondary-fixed": "#1a1c1a",
        "on-secondary-fixed-variant": "#464745",
        "tertiary": "#735c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#cca730",
        "on-tertiary-container": "#4f3e00",
        "tertiary-fixed": "#ffe088",
        "tertiary-fixed-dim": "#e9c349",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#574500",
        "surface": "#faf9f9",
        "surface-bright": "#faf9f9",
        "surface-dim": "#dbdad9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#e9e8e8",
        "surface-container-highest": "#e3e2e2",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e3e2e2",
        "on-surface-variant": "#444748",
        "surface-tint": "#5f5e5e",
        "on-background": "#1b1c1c",
        "background": "#faf9f9",
        "inverse-surface": "#2f3031",
        "inverse-on-surface": "#f2f0f0",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "32px",
        "margin-desktop": "64px",
        "container-max": "1440px",
        unit: "8px",
        "margin-mobile": "24px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        caption: ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        serif: ["Playfair Display", "serif"],
        sans: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "600" }],
        caption: ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "300" }],
        "display-lg": ["84px", { lineHeight: "92px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
